<?php declare(strict_types=1);
# Generated by the OpenSwoole compiler. DO NOT EDIT!
# source: service_job_queue.proto

namespace Grpc\Interconnect;

use OpenSwoole\GRPC;

interface HostInterface extends GRPC\ServiceInterface
{
    public const NAME = "/grpc.interconnect.Host";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param MessageRequest $request
    * @return MessageResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Message(GRPC\ContextInterface $ctx, MessageRequest $request): MessageResponse;
}
