<?php declare(strict_types=1);
# Generated by the OpenSwoole compiler. DO NOT EDIT!
# source: service_job_queue.proto

namespace Grpc\Interconnect;

use OpenSwoole\GRPC;

class HostClient extends \OpenSwoole\GRPC\BaseStub
{


    /**
    * @param MessageRequest $request
    * @return MessageResponse
    *
    * @throws \OpenSwooleGRPC\Exception\InvokeException
    */
    public function Message(MessageRequest $request, $metadata = []): MessageResponse {
    	return $this->_simpleRequest('/grpc.interconnect.Host/Message',
        $request,
        ['\Grpc\Interconnect\MessageResponse', 'decode'],
        $metadata); 
    }
}
