<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_response.proto

namespace GPBMetadata;

class MessageResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a680a166d6573736167655f726573706f6e73652e70726f746f12116772" .
            "70632e696e746572636f6e6e65637422330a0f4d65737361676552657370" .
            "6f6e7365120f0a0773756363657373180120012808120f0a076d65737361" .
            "6765180220012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

