<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message_request.proto

namespace GPBMetadata;

class MessageRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a630a156d6573736167655f726571756573742e70726f746f1211677270" .
            "632e696e746572636f6e6e656374222f0a0e4d6573736167655265717565" .
            "7374120c0a046e616d65180120012809120f0a076d657373616765180220" .
            "012809620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

