<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_job_queue.proto

namespace GPBMetadata;

class ServiceJobQueue
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\MessageRequest::initOnce();
        \GPBMetadata\MessageResponse::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0aa6010a17736572766963655f6a6f625f71756575652e70726f746f1211" .
            "677270632e696e746572636f6e6e6563741a166d6573736167655f726573" .
            "706f6e73652e70726f746f32580a04486f737412500a074d657373616765" .
            "12212e677270632e696e746572636f6e6e6563742e4d6573736167655265" .
            "71756573741a222e677270632e696e746572636f6e6e6563742e4d657373" .
            "616765526573706f6e7365620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

